### ISSUE TITLE
Connected + Clear Glass Frame not moving

### ISSUE THREAD

**Issue by nickweibel** [amadornes/Framez#25]
In modsause I am unable to get a 3x3x1 structure of frames to move. If I use unmodified frames it works fine, but connected with clear glass will not move.

Using Redstone Flux Motor

**Comment by amadornes** [comment]
The tooltip of the frames tells you how many blocks each frame can move (including itself). The glass frames can't move any blocks because they're not solid and robust enough to support other blocks, therefore you're trying to move 9 blocks (3x3x1) with 9 frames, which add 0 blocks each to the maximum amount that can be moved. This means you're trying to move 9 blocks with a max moved amount of 1 (the one added by the motor).
To get around this you can place two iron frames anywhere in the structure, which will add 10 to the block cap, making it 11, and that is enough to move your 9 glass frames and the 2 iron frames.

Another option would be making the entire door out of normal connected frames and place Thickened Glass covers on the sides you want to be transparent so the "cross" disappears and they look transparent. On the other sides... I'll leave that up to you, if you also want to make them out of glass so they're see-through or some other material ;)

And yes, I know this feature is a bit confusing and that's why I'm going to change it in the next release (a complete rewrite of the mod) with a system that takes into account the amount of blocks around a frame instead of having a block cap for the entire structure. And glass frames will also be able to support themselves, allowing you to do this build without any other frames :P
There are lots of features I'm working on that I haven't told anybody about, but I think some of them will be really cool to play around with ;)

Here's a screenshot of the new frames and motors in the world: http://gyazo.com/0a325f3aa921cd21bfc80b478f5517af
I thought I'd keep the vanilla look by making the textures 16x16 instead of 32x32 and making them look more robust by making the borders thicker. There's also an easy way to differentiate between covers and panels now, just like in RedPower. I've also added a GUI to the wrench that allows you to make the frames click-through, so you can interact with what's in them more easily (http://gyazo.com/ed2989d3bbf99211ae2603f92bd1cce1) and an option to render them in 2D for the people with lower end computers (http://gyazo.com/a24d382f64bab7e97d809cd76b5b2dfd). :P
I really love building up the hype, don't I? xD

**Comment by nickweibel** [comment]
Thank you so much for the reply. I didn't see the tooltips, but what your saying sounds reasonable. I'll try what you suggested with the glass covers. 

You've got a great mod and I look forward to future updates.

**Comment by amadornes** [comment]
Thanks :D
