### ISSUE TITLE
AE2 Motor crash

### ISSUE THREAD

**Issue by Dominance** [amadornes/Framez#9]
http://pastebin.com/DrTs4feR Not exactly sure how it was set up.

**Comment by amadornes** [comment]
There's no motor for AE2 power anymore, although it may get added again at some point. Since this was an issue with Framez 1 and the motor isn't there anymore. Therefore, I'm closing this issue.
From now on you can power your motors with RF, EU, Botania mana and PneumaticCraft pressure, with many more options to come! :)
